# baseURL = "https://your_domain.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Tahraga Transactions Bio"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  # name = "Tahraga"
  # headline = "Transactions follow up services"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
    # { email = "mailto:info@tahragatransaction.ae" },
    # { link = "www.tahragatransactions.ae" },
    # { Maps = "https://www.google.com/" },
    # {Facebook = "Facebook.com/tahraga-transactions}
    # { instagram = "https://instagram.com/tahraga.transactions" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
